<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>parent</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <modules>
  	<module>core</module>
  </modules>
  <properties>
  	<spring.boot.dependencies.version>2.7.18</spring.boot.dependencies.version>
  	<spring.cloud.dependencies.version>2021.0.6</spring.cloud.dependencies.version>
  	<spring.boot.version>3.3.4</spring.boot.version>
  	<open-saml-version>4.2.0</open-saml-version>
  </properties>
  <dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-dependencies</artifactId>
			<version>${spring.boot.dependencies.version}</version>
			<type>pom</type>
	  	</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>${spring.cloud.dependencies.version}</version>
			<type>pom</type>
	  	</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<version>${spring.boot.dependencies.version}</version>
	  	</dependency>
	  	<dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<version>1.30</version>
	  	</dependency>
  		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.13.5</version>
	  	</dependency>
  		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.13.5</version>
	  	</dependency>
  		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
			<version>2.13.5</version>
	  	</dependency>
  		<dependency>
			<groupId>com.fasterxml.jackson.module</groupId>
			<artifactId>jackson-module-parameter-names</artifactId>
			<version>2.13.5</version>
	  	</dependency>
  		<dependency>
			<groupId>org.opemsaml</groupId>
			<artifactId>opensaml-core</artifactId>
			<version>${open-saml-version}</version>
	  	</dependency>
  		<dependency>
			<groupId>org.opemsaml</groupId>
			<artifactId>opensaml-saml-impl</artifactId>
			<version>${open-saml-version}</version>
	  	</dependency>
	  </dependencies>
  </dependencyManagement>
  
      <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.8.0</version>
                <executions>
                    <execution>
                        <id>write-dependency-tree</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>tree</goal>
                        </goals>
                        <configuration>
                            <outputFile>C:\Users\Anurag Kulkarni\OneDrive\Desktop\POMS\tempPOMForDirectDependencies\dependency-tree.json</outputFile>
                            <outputType>json</outputType>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>10.0.4</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <formats>
                        <format>JSON</format>
                    </formats>
                    <outputDirectory>C:\Users\Anurag Kulkarni\OneDrive\Desktop\POMS\tempPOMForDirectDependencies</outputDirectory>
                    <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                    <golangDepEnabled>false</golangDepEnabled>
                    <nuspecAnalyzerEnabled>false</nuspecAnalyzerEnabled>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.17.1</version>
            </plugin>
        </plugins>
    </build>
</project>